
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Serhad
 */
public class kutuphane_yonetim_giris extends javax.swing.JFrame {
Connection conn=null; PreparedStatement pst=null; ResultSet rst=null; 
    /**
     * Creates new form kutuphane_yonetim_giris
     */
    public kutuphane_yonetim_giris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_kullaniciadi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_kullanicisifre = new javax.swing.JPasswordField();
        btn_kullanıcıkayıt = new javax.swing.JButton();
        btn_kullanicigiris = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KULLANICI GİRİŞİ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 420, 60));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("KULLANICI ADI");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 102, 189, 44));

        txt_kullaniciadi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_kullaniciadi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_kullaniciadi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(txt_kullaniciadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 103, 207, 44));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ŞİFRE");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 189, 44));

        txt_kullanicisifre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_kullanicisifre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_kullanicisifre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(txt_kullanicisifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 165, 207, 44));

        btn_kullanıcıkayıt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_kullanıcıkayıt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kullanıcı adı.png"))); // NOI18N
        btn_kullanıcıkayıt.setText("KULLANICI KAYIT");
        btn_kullanıcıkayıt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_kullanıcıkayıt.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_kullanıcıkayıt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kullanıcıkayıtActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kullanıcıkayıt, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 220, 180, 42));

        btn_kullanicigiris.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_kullanicigiris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kullanıcı giriş buton.png"))); // NOI18N
        btn_kullanicigiris.setText("GİRİŞ");
        btn_kullanicigiris.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_kullanicigiris.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_kullanicigiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kullanicigirisActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kullanicigiris, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 220, 117, 42));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/19220.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 420, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kullanicigirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kullanicigirisActionPerformed
        if (!(txt_kullaniciadi.getText().equals(""))&&!(txt_kullanicisifre.getText().equals(""))) {
           try
        {
            conn=k_db.conn_db();//1
            String sql="SELECT * FROM KULLANICILAR WHERE KULLANICI_ADI='"+txt_kullaniciadi.getText()
                    +"' AND SİFRE='"+txt_kullanicisifre.getText()+"'";//2
            pst = conn.prepareStatement(sql); // 3
            rst = pst.executeQuery(); //4
            
            if (rst.next()) {
                JOptionPane.showMessageDialog(null, "Giriş başarılı");
                kutuphane_yonetim frame=new kutuphane_yonetim();
                frame.setVisible(true);
                this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Kullanıcı adı veya şifreniz yanlış!");
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        finally
        {
            try
            {
                conn.close();//5
            }
            catch(Exception ex)
            {
                
            }
        }
        }
        else{
           JOptionPane.showMessageDialog(null, "Lütfen İlgili Boşlukları Doldurunuz!");  
        }
    }//GEN-LAST:event_btn_kullanicigirisActionPerformed

    private void btn_kullanıcıkayıtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kullanıcıkayıtActionPerformed
        kutuphane_yonetim_kullanicikayit frame=new kutuphane_yonetim_kullanicikayit();
           frame.setVisible(true);
            this.setVisible(false);
        
    }//GEN-LAST:event_btn_kullanıcıkayıtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kutuphane_yonetim_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kutuphane_yonetim_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kutuphane_yonetim_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kutuphane_yonetim_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kutuphane_yonetim_giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kullanicigiris;
    private javax.swing.JButton btn_kullanıcıkayıt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_kullaniciadi;
    private javax.swing.JPasswordField txt_kullanicisifre;
    // End of variables declaration//GEN-END:variables
}
