
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Serhad
 */
public class kutuphane_yonetim_kullanicikayit extends javax.swing.JFrame {
Connection conn=null; PreparedStatement pst=null; ResultSet rst=null; 
    /**
     * Creates new form kutuphane_yonetim_kullanicikayit
     */
    public kutuphane_yonetim_kullanicikayit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_kullanicikayitad = new javax.swing.JTextField();
        txt_kullanicikayitsifre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_kullanicikayitmail = new javax.swing.JTextField();
        btn_kayit = new javax.swing.JButton();
        btn_girisekran = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("KULLANICI KAYIT EKRANI");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 390, 46));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("KULLANICI ADI");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 150, 42));

        txt_kullanicikayitad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_kullanicikayitad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_kullanicikayitad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_kullanicikayitad.setPreferredSize(new java.awt.Dimension(104, 21));
        jPanel1.add(txt_kullanicikayitad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 167, 42));

        txt_kullanicikayitsifre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_kullanicikayitsifre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_kullanicikayitsifre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_kullanicikayitsifre.setPreferredSize(new java.awt.Dimension(104, 21));
        jPanel1.add(txt_kullanicikayitsifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 167, 42));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ŞİFRE");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 150, 42));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("E-MAİL");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 150, 42));

        txt_kullanicikayitmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_kullanicikayitmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_kullanicikayitmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_kullanicikayitmail.setPreferredSize(new java.awt.Dimension(104, 21));
        jPanel1.add(txt_kullanicikayitmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 167, 42));

        btn_kayit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_kayit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tik.png"))); // NOI18N
        btn_kayit.setText("KAYIT OL");
        btn_kayit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_kayit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 104, 38));

        btn_girisekran.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_girisekran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geri (2).png"))); // NOI18N
        btn_girisekran.setText("GİRİŞ EKRANINA DÖN");
        btn_girisekran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_girisekran.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_girisekran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisekranActionPerformed(evt);
            }
        });
        jPanel1.add(btn_girisekran, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 200, 38));

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resetle.png"))); // NOI18N
        jButton1.setText("RESETLE");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 110, 38));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kullanıcı kayıt arka plan (2).jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, -1, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitActionPerformed
        if (!(txt_kullanicikayitad.getText().equals(""))&&(!(txt_kullanicikayitsifre.getText().equals("")))&&(!(txt_kullanicikayitmail.getText().equals("")))) {
try
        {
            conn=k_db.conn_db();//
String sql06="INSERT INTO KULLANICILAR (KULLANICI_ADI, SİFRE, EMAIL)\n" +
"VALUES (?,?,?);";//2
            pst = conn.prepareStatement(sql06); // 3
            pst.setString(1, txt_kullanicikayitad.getText());
            pst.setString(2, txt_kullanicikayitsifre.getText());
            pst.setString(3, txt_kullanicikayitmail.getText());
            pst.execute(); //4
            JOptionPane.showMessageDialog(null, "KAYIT BAŞARIYLA EKLENMİŞTİR");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        finally
        {
            try
            {
                conn.close();//5
            }
            catch(Exception ex)
            {
                
            }
        } 
        }
        else  {
            JOptionPane.showMessageDialog(null, "Lütfen İlgili Boşlukları Doldurunuz!");
        } 
    }//GEN-LAST:event_btn_kayitActionPerformed

    private void btn_girisekranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisekranActionPerformed
        kutuphane_yonetim_giris frame=new kutuphane_yonetim_giris();
           frame.setVisible(true);
            this.setVisible(false);
            
    }//GEN-LAST:event_btn_girisekranActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        metot.txtfieldreset(txt_kullanicikayitad);
        metot.txtfieldreset(txt_kullanicikayitsifre);
        metot.txtfieldreset(txt_kullanicikayitmail);
    }//GEN-LAST:event_jButton1ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kutuphane_yonetim_kullanicikayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kutuphane_yonetim_kullanicikayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kutuphane_yonetim_kullanicikayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kutuphane_yonetim_kullanicikayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kutuphane_yonetim_kullanicikayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_girisekran;
    private javax.swing.JButton btn_kayit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_kullanicikayitad;
    private javax.swing.JTextField txt_kullanicikayitmail;
    private javax.swing.JTextField txt_kullanicikayitsifre;
    // End of variables declaration//GEN-END:variables
}
